# Streamlit Cloud Secrets Configuration Template
# ⚠️ 이 내용을 Streamlit Cloud Dashboard의 Secrets 섹션에 입력하세요
# ⚠️ 절대 이 파일을 실제 값과 함께 GitHub에 커밋하지 마세요!

# ========================================
# API Keys (필수)
# ========================================
# 법제처 Open API Key
# https://open.law.go.kr 에서 발급
LAW_API_KEY = "your-actual-law-api-key-here"

# OpenAI API Key  
# https://platform.openai.com 에서 발급
OPENAI_API_KEY = "sk-your-actual-openai-api-key-here"

# ========================================
# Application Settings (선택)
# ========================================
[app_settings]
DEFAULT_GPT_MODEL = "o3"
CACHE_TTL = 3600
DEBUG = false
MAX_REQUESTS_PER_MINUTE = 60
MAX_TOKENS_PER_REQUEST = 3000

# ========================================
# Feature Flags (선택)
# ========================================
[features]
ENABLE_TREATY_SEARCH = true
ENABLE_COMMITTEE_SEARCH = true
ENABLE_LOCAL_LAW_SEARCH = true
ENABLE_AI_ANALYSIS = true
