# Streamlit Cloud Secrets Configuration
# This file is for Streamlit Cloud deployment
# DO NOT commit this file to version control
# Add these secrets in Streamlit Cloud dashboard instead

# ========================================
# API Keys
# ========================================

# 법제처 Open API Key
LAW_API_KEY = "your_actual_law_api_key_here"

# OpenAI API Key
OPENAI_API_KEY = "sk-your_actual_openai_api_key_here"

# ========================================
# Application Settings
# ========================================

[app_settings]
DEFAULT_GPT_MODEL = "o3"
CACHE_TTL = 3600
DEBUG = false
MAX_REQUESTS_PER_MINUTE = 60
MAX_TOKENS_PER_REQUEST = 3000

# ========================================
# Feature Flags
# ========================================

[features]
ENABLE_TREATY_SEARCH = true
ENABLE_COMMITTEE_SEARCH = true
ENABLE_LOCAL_LAW_SEARCH = true
ENABLE_AI_ANALYSIS = true

# ========================================
# Database Configuration (Optional)
# ========================================

# [database]
# url = "sqlite:///search_history.db"
# pool_size = 5
# max_overflow = 10

# ========================================
# Redis Configuration (Optional)
# ========================================

# [redis]
# host = "localhost"
# port = 6379
# db = 0
# password = ""

# ========================================
# Logging Configuration
# ========================================

[logging]
level = "INFO"
file = "app.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# ========================================
# Security Settings
# ========================================

[security]
# Session timeout in minutes
SESSION_TIMEOUT = 60

# Enable HTTPS only
HTTPS_ONLY = true

# Allowed origins for CORS
ALLOWED_ORIGINS = ["https://share.streamlit.io"]

# ========================================
# Rate Limiting
# ========================================

[rate_limiting]
# Per user limits
MAX_SEARCHES_PER_HOUR = 100
MAX_AI_ANALYSES_PER_HOUR = 20

# Global limits
MAX_CONCURRENT_USERS = 100

# ========================================
# IMPORTANT NOTES
# ========================================

# 1. For local development:
#    - Copy this file to .streamlit/secrets.toml
#    - Fill in your actual API keys
#    - Never commit with real keys

# 2. For Streamlit Cloud deployment:
#    - Go to your app dashboard
#    - Click on "Settings" → "Secrets"
#    - Copy the content (with real keys) there
#    - Do NOT include this file in your repository

# 3. Accessing secrets in code:
#    import streamlit as st
#    law_api_key = st.secrets["LAW_API_KEY"]
#    openai_key = st.secrets["OPENAI_API_KEY"]
